# Generated by Django 2.2.5 on 2020-02-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_uploadimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagemodel',
            name='name',
            field=models.CharField(default='temp_image', max_length=255),
        ),
    ]
