# Generated by Django 2.2.5 on 2020-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_uploadimagemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tensorflowmodel',
            name='model_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
