# Generated by Django 2.2.5 on 2020-03-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tensorflowmodel_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearningTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('supervised_type', models.CharField(max_length=20)),
            ],
        ),
    ]
